package master;

//和ZooKeeper通信函数的返回值类型
public enum ResType {
    ADD_REGION_SUCCESS,
    ADD_REGION_FAILURE,
    ADD_REGION_ALREADY_EXISTS,
    DROP_REGION_SUCCESS,
    DROP_REGION_FAILURE,
    DROP_REGION_NO_EXISTS,
    CREATE_TABLE_SUCCESS,
    CREATE_TABLE_FAILURE,
    DROP_TABLE_SUCCESS,
    DROP_TABLE_FAILURE,
    INSERT_SUCCESS,
    INSERT_FAILURE,
    INSERT_TABLE_NO_EXISTS,
    DELECT_SUCCESS,
    DELECT_FAILURE,
    DELECT_TABLE_NO_EXISTS,
    FIND_SUCCESS,
    FIND_FAILURE,
    FIND_TABLE_NO_EXISTS,
    TRUNCATE_SUCCESS,
    TRUNCATE_FAILURE,
    TRUNCATE_TABLE_NO_EXISTS,
}